### PR TITLE
Ensure 'normal' status codes are not treated as errors

### PR DESCRIPTION
**Pull request by Crosse**
I can't get `notifu.exe` to wait at all for user interaction with the notification balloon, so I couldn't test that this actually fixes the issue, although I'm pretty confident it would.

### CODE REVIEW

**Comment by myleshorton** [comment]
What does it do instead of waiting for user interaction @Crosse?

**Comment by Crosse** [comment]
It just returns immediately with an exit status of 0. I had a thought this morning while driving that it might behave differently when run using Go's `exec.Command()`, but that seems like a long shot. I'm also on Windows 11, so I want to try it on Windows 10 today. Maybe it's broken on Windows 11...?

**Comment by Crosse** [comment]
Nope, not a Windows 11 vs Windows 10 thing. I get the same behavior on my Windows 10 VM.

**Comment by Crosse** [comment]
IT DOES ACT DIFFERENTLY RUNNING FROM GO. Well, then.

Alright, I've tested this with most of the return codes specified here and the change works:

https://github.com/getlantern/notifier/blob/20d929234885e96b6ac3db61abd185ae48d5b17e/notifier_windows.go#L39-L48

**Comment by Crosse** [comment]
Some linter was complaining that I didn't use a Go raw string (`` `blah` ``) for the regex, so I fixed it and force-pushed. This should be good for actual review now.

**Comment by myleshorton** [comment]
So wait the notifications appear correctly then right?

**Review by myleshorton — APPROVED** [review]

**Comment by Crosse** [comment]
They do.

**Pull request merged**
